/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import contoller.VendedorController;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.bean.Vendedor;

/**
 *
 * @author joseo
 */
public class TelaCadastroVendedor extends javax.swing.JInternalFrame {

    private javax.swing.table.DefaultTableModel tabelaModelo;
    private VendedorController vController;
    private Vendedor vSelecionado = new Vendedor();
    private boolean podeEditar = false;

    /**
     * Creates new form cadastroDeLivros
     */
    public TelaCadastroVendedor() {
        vController = new VendedorController();
        CriarTabelaModelo();
        initComponents();
        vController.listarTodos(tabelaModelo);
        limparCampos();
    }

    public void CriarTabelaModelo() {

        tabelaModelo = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null}
                },
                new String[]{
                    "Código", "CPF", "Nome", "Endereço", "Status"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

        };
    }

    public void preencherSelecionado(ListSelectionEvent e) {
        int linha = tabelaDeVendedores.getSelectedRow();
        try {
            int id = Integer.parseInt(tabelaModelo.getValueAt(linha, 0).toString());
            String CPF = tabelaModelo.getValueAt(linha, 1).toString();
            String nome = tabelaModelo.getValueAt(linha, 2).toString();
            String endereco = tabelaModelo.getValueAt(linha, 3).toString();
            boolean status = tabelaModelo.getValueAt(linha, 4).toString().equals("1 - Ativo");

            this.preencherVendedor(vSelecionado, id, CPF, nome, endereco, status);

            this.preencherCampos();
            this.habilitarCamposEdicao();
        } catch (Exception erro) {
            this.limparCampos();
        }
    }

    public void preencherVendedor(Vendedor v, int id, String CPF, String nome, String endereco, boolean status) {
        if (CPF != null && nome != null && endereco != null) {
            v.setId(id);
            v.setCPF(CPF);
            v.setNome(nome);
            v.setEndereco(endereco);
            v.setStatus(status);
        } else {
            this.limparCampos();
        }
    }

    public void preencherCampos() {
        CPFText.setText(vSelecionado.getCPF());
        nomeText.setText(vSelecionado.getNome());
        enderecoText.setText(vSelecionado.getEndereco());
        String status_index = vSelecionado.isStatus() ? "1 - Ativo" : "2 - Inativo";
        statusLista.getModel().setSelectedItem(status_index);
    }

    public void limparCampos() {
        vSelecionado = new Vendedor(); // Limpar vendedor selecionado

        CPFText.setText("");
        nomeText.setText("");
        enderecoText.setText("");
        String status_index = "2 - Inativo";
        statusLista.getModel().setSelectedItem(status_index);

        tabelaDeVendedores.getSelectionModel().clearSelection();
        this.desabilitarCamposEdicao();
    }
    
    public void desabilitarCamposEdicao() {
        this.CPFText.setEnabled(false);
        this.nomeText.setEnabled(false);
        this.enderecoText.setEnabled(false);
        this.statusLista.setEnabled(false);
        
        this.podeEditar = false;
    }
    
    public void habilitarCamposEdicao() {
        this.CPFText.setEnabled(true);
        this.nomeText.setEnabled(true);
        this.enderecoText.setEnabled(true);
        this.statusLista.setEnabled(true);
        
        this.podeEditar = true;
    }

    // Selecionar linhas na tabela
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeVendedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CPFText = new javax.swing.JTextField();
        nomeText = new javax.swing.JTextField();
        enderecoText = new javax.swing.JTextField();
        statusLista = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadasro de Vendores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaDeVendedores.setModel(tabelaModelo);
        tabelaDeVendedores.getTableHeader().setReorderingAllowed(false);
        tabelaDeVendedores.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                preencherSelecionado(e);
            }
        });
        jScrollPane1.setViewportView(tabelaDeVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, 740, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CPF:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ENDEREÇO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("STATUS CADASTRO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CPFText.setText("000.000.000-00");
        getContentPane().add(CPFText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 285, -1));

        nomeText.setText("Nome Completo");
        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });
        getContentPane().add(nomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 285, -1));

        enderecoText.setText("Rua, Numero, Cidade - UF");
        getContentPane().add(enderecoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 285, -1));

        statusLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Ativo", "0 - Inativo" }));
        getContentPane().add(statusLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 285, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, 60));

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, 60));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 110, 60));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 110, 60));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 430));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Book Store");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 290, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (!this.podeEditar) {
            JOptionPane.showMessageDialog(this, "Selecione um vendor na tabela ou clique em NOVO.\nÉ preciso preencher todos os campos.");
            return;
        }
        
        int id = vSelecionado.getId();
        String CPF = CPFText.getText();
        String nome = nomeText.getText();
        String endereco = enderecoText.getText();
        boolean status = statusLista.getSelectedItem().toString().equals("1 - Ativo");

        this.preencherVendedor(vSelecionado, id, CPF, nome, endereco, status);

        if (vSelecionado != null && !(CPF.equals("") || nome.equals("") || endereco.equals("") )) {
            if (vSelecionado.getId() != 0) {
                // atualizar
                vController.salvar(tabelaModelo, vSelecionado, false);
            } else {
                // criar novo
                vController.salvar(tabelaModelo, vSelecionado, true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "É preciso preencher todos os campos.");
        }

        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (vSelecionado == null) {
            JOptionPane.showMessageDialog(this, "O Vendedor selecionado não existe no banco de dados.\nTente selecionar um vendedor da tabela abaixo." );
        } else {
            vController.excluir(tabelaModelo, vSelecionado);
        }

        limparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        // TODO add your handling code here:
        Object[] possibilities = {"Todos", "Pelo Código", "Pelo CPF"};
        String escolha = (String) JOptionPane.showInputDialog(
                this,
                "Escolha o tipo de busca\n"
                + "que deseja efetuar",
                "Buscar Vendedor",
                JOptionPane.QUESTION_MESSAGE,
                null,
                possibilities,
                possibilities[0]);
        
        escolha = escolha == null ? "" : escolha;

        switch (escolha) {
            case "Pelo Código":
                int id = Integer.parseInt(JOptionPane.showInputDialog(this, "Código do Vendedor: "));
                vController.listarPorId(tabelaModelo, id);
                break;
            case "Pelo CPF":
                String CPF = JOptionPane.showInputDialog(this,"CPF do Vendedor: ");
                vController.listarPorCPF(tabelaModelo, CPF);
                break;
            default:
                vController.listarTodos(tabelaModelo);
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarCamposEdicao();
        this.CPFText.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPFText;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField enderecoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeText;
    private javax.swing.JComboBox<String> statusLista;
    private javax.swing.JTable tabelaDeVendedores;
    // End of variables declaration//GEN-END:variables

}
